### ISSUE TITLE
The application still has some bugs

### ISSUE THREAD

**Issue by AssassinRain** [ligi/PassAndroid#228]
Hello. I noticed some crashes in logs.  The corresponding commit version of code is  a6baee2, and application version is 3.4.7. 
## 1.org.ligi.passandroid.ui.PassViewActivity
The exception trace is: 
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to resume activity {org.ligi.passandroid/org.ligi.passandroid.ui.PassViewActivity}: kotlin.UninitializedPropertyAccessException: lateinit property currentPass has not been initialized
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3790)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3830)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3038)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property currentPass has not been initialized
	at org.ligi.passandroid.ui.PassViewActivityBase.g(SourceFile:34)
	at org.ligi.passandroid.ui.PassViewActivity.f(SourceFile:49)
	at org.ligi.passandroid.ui.PassViewActivity.onResumeFragments(SourceFile:130)
	at android.support.v4.app.FragmentActivity.onPostResume(SourceFile:498)
	at android.support.v7.app.AppCompatActivity.onPostResume(SourceFile:172)
	at android.app.Activity.performResume(Activity.java:7385)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3765)*
## 2.org.ligi.passandroid.ui.quirk_fix.URLRewriteActivity
The exception trace is: 
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ligi.passandroid/org.ligi.passandroid.ui.quirk_fix.URLRewriteActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.b, parameter uri
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.b, parameter uri
	at org.ligi.passandroid.ui.quirk_fix.URLRewriteController.a(Unknown Source:16)
	at org.ligi.passandroid.ui.quirk_fix.URLRewriteActivity.onCreate(SourceFile:17)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
## 3.org.ligi.passandroid.ui.ExtractURLAsIphoneActivity
The exception trace is: 
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ligi.passandroid/org.ligi.passandroid.ui.ExtractURLAsIphoneActivity}: java.lang.IllegalStateException: intent.data must not be null
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: intent.data must not be null
	at org.ligi.passandroid.ui.ExtractURLAsIphoneActivity.onCreate(SourceFile:26)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
## 4.org.ligi.passandroid.ui.quirk_fix.USAirwaysLoadActivity
The exception trace is: 
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ligi.passandroid/org.ligi.passandroid.ui.quirk_fix.USAirwaysLoadActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
	at org.ligi.passandroid.ui.quirk_fix.USAirwaysLoadActivity.onCreate(SourceFile:15)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
### The command to trigger it is: adb shell am start org.ligi.passandroid/org.ligi.passandroid.ui.quirk_fix.USAirwaysLoadActivity

Because all these activities are exported ones, i.e., be exposed to outside, they may receive unfriendly commands and then lead to app crash.  After investigation, we found that the missing of null checkers causes those crashes. 
Please help to confirm whether they are true bugs. We believe that fixing these bugs will further improve the robustness of this app.

**Comment by simontb** [comment]
Hi,

thanks for reporting this issue.

The adb call is not a correct usage of the app, but in any case it should fail gracefully (e.g. by showing a message that parameters haven't been passed to this Activity).

For me there is no high priority to fix these issues, but feel free to open a PR.

**Comment by AssassinRain** [comment]
Thanks for your kindly reply.
After compile the latest version into an apk and retest, we find that the same crash still can be triggered.
Besides, we also find two new bugs.
The detailed information are as follows:
## 1.com.mikifus.padland.PadViewActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikifus.padland/com.mikifus.padland.PadViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mikifus.padland.Models.Pad.getUrl()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mikifus.padland.Models.Pad.getUrl()' on a null object reference
	at com.mikifus.padland.PadViewActivity._getPadId(PadViewActivity.java:311)
	at com.mikifus.padland.PadViewActivity._getPadData(PadViewActivity.java:251)
	at com.mikifus.padland.PadViewActivity._makePadUrl(PadViewActivity.java:218)
	at com.mikifus.padland.PadViewActivity.onCreate(PadViewActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
### The command to trigger it is: adb shell am start -n com.mikifus.padland/com.mikifus.padland.PadViewActivity
## 2.com.mikifus.padland.PadViewActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikifus.padland/com.mikifus.padland.PadViewActivity}: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1975)
	at com.mikifus.padland.PadViewActivity.makePadData(PadViewActivity.java:641)
	at com.mikifus.padland.PadViewActivity._getPadDataFromIntent(PadViewActivity.java:291)
	at com.mikifus.padland.PadViewActivity._getPadId(PadViewActivity.java:310)
	at com.mikifus.padland.PadViewActivity._getPadData(PadViewActivity.java:251)
	at com.mikifus.padland.PadViewActivity._makePadUrl(PadViewActivity.java:218)
	at com.mikifus.padland.PadViewActivity.onCreate(PadViewActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
### The command to trigger it is: adb shell am start -n com.mikifus.padland/com.mikifus.padland.PadViewActivity -a android.intent.action.VIEW
## 3.com.mikifus.padland.PadListActivity
The exception trace is:
*FATAL EXCEPTION: main
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mikifus.padland/com.mikifus.padland.PadListActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.mikifus.padland.PadListActivity.i(SourceFile:3)
	at com.mikifus.padland.PadListActivity.onCreate(SourceFile:2)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
### And there are the parameters of our intent: *action*: null;; *category*: null;; *data*: null;; *type*: null;; *extra-data*: String->android.intent.extra.TEXT->abcde,Extras->ExtrasObj->ExtrasObj,(,long->focus_pad->0,),String->action->abcde

**Comment by AssassinRain** [comment]
OK, we have submitted a PR with commit version 7ce5bfc.

**Comment by ligi** [comment]
@AssassinRain thanks for the PR - looks good on a first glance. But I am currently at CCCamp2019 and can only merge it afterwards. Perhaps @simontb can also have a look before

**Comment by AssassinRain** [comment]
OK, we have submitted a PR with another commit version b81f79d.
