### ISSUE TITLE
App does not start anymore: NoSuchMethodException

### ISSUE THREAD

**Issue by simontb** [ligi/PassAndroid#247]
When opening the app (either via launcher or widget to a pass) I only see a blank screen and the app crashing. Logcat:

```
2020-03-03 20:39:25.238 5482-5482/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.ligi.passandroid, PID: 5482
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ligi.passandroid/org.ligi.passandroid.ui.PassListActivity}: java.lang.NoSuchMethodException: parameter type is null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.NoSuchMethodException: parameter type is null
        at java.lang.Class.getConstructor0(Class.java:2326)
        at java.lang.Class.getDeclaredConstructor(Class.java:2170)
        at org.ligi.passandroid.model.pass.BarCodeJsonAdapter.fromJson(SourceFile:14)
        at org.ligi.passandroid.model.pass.BarCodeJsonAdapter.fromJson(SourceFile:1)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(SourceFile:3)
        at org.ligi.passandroid.model.pass.PassImplJsonAdapter.fromJson(SourceFile:18)
        at org.ligi.passandroid.model.pass.PassImplJsonAdapter.fromJson(SourceFile:1)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(SourceFile:3)
        at com.squareup.moshi.JsonAdapter.fromJson(SourceFile:1)
        at org.ligi.passandroid.model.AndroidFileSystemPassStore.readPass(SourceFile:7)
        at org.ligi.passandroid.model.AndroidFileSystemPassStore.getPassbookForId(SourceFile:1)
        at org.ligi.passandroid.model.AndroidFileSystemPassStore.syncPassStoreWithClassifier(SourceFile:4)
        at org.ligi.passandroid.ui.PassListActivity.onCreate(SourceFile:17)
        at android.app.Activity.performCreate(Activity.java:7825)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
2020-03-03 20:39:25.613 618-618/? E/Layer: [Surface(name=AppWindowToken{893c34d token=Token{bb062e4 ActivityRecord{299f677 u0 org.ligi.passandroid/.ui.PassListActivity t14757}}})/@0x2ea9681 - animation-leash#0] No local sync point found
2020-03-03 20:39:25.613 618-618/? E/Layer: [Surface(name=AppWindowToken{893c34d token=Token{bb062e4 ActivityRecord{299f677 u0 org.ligi.passandroid/.ui.PassListActivity t14757}}})/@0x2ea9681 - animation-leash#0] No local sync point found
2020-03-03 20:39:29.241 5482-5482/? D/PassAndroid: Writing unhandled exception to: /data/user/0/org.ligi.passandroid/files/3.5.4-1583264369241.tracedroid
2020-03-03 20:39:29.242 5482-5482/? D/PassAndroid: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.ligi.passandroid/org.ligi.passandroid.ui.PassListActivity}: java.lang.NoSuchMethodException: parameter type is null
```

**Comment by simontb** [comment]
App version is 3.5.4 (latest from Play Beta)

**Comment by simontb** [comment]
A fresh debug build from master works. Either new code has been pushed to master in the meantime (which I doubt as bump version to 3.5.4 is the latest commit) or it is related to one of my passes/config. I'll further investigate, but don't know where to start.

Is there any way to backup all passes via adb and move them to the second application (I use `applicationIdSuffix '.debug')?

**Comment by ligi** [comment]
Hey - thanks for investigating. Currently there is no straight forward way to copy passes. But this is a feature that is very often requested anyway - so will need for care for this soon. But first fix the issue here.
Looks a bit like a proguard problem as I do not see it in debug currently

**Comment by simontb** [comment]
Ah, I think you're right. When I researched this issue, I stumpled across this issue: https://github.com/square/moshi/issues/1049

Maybe this is the same or a similiar issue. I don't know tbh, because I'm not very familiar with proguard and R8. But if I find out more, I'll let you know or open a PR.

**Comment by ligi** [comment]
thanks! Could (and should) also look into this tonight - there are more and more reports with this problem (unfortunately I already started a staged rollout with 5%) - but would also be happy if you look into this and e.g. try if https://github.com/square/moshi/issues/1049#issuecomment-592453233 works.

**Comment by simontb** [comment]
Thanks @ligi for the quick merge and upload to Play beta. I can now confirm that this solved the issue on my Pixel 4 as well 👍🏻
