### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by rugk** [ligi/PassAndroid#519]
## STR

1. Just started app after a while after importing/opening two *.pkass files via the file manager.
2. But the last start was usual via the main screen.

## Logs

```
file: /data/user/0/org.ligi.passandroid/files/3.7.3-1702746299378.tracedroid
Android Version: 13
Phone Model: FP4\nTraceDroid Version: 4.1\nStacktrace: java.lang.RuntimeException: Unable to resume activity {org.ligi.passandroid/org.ligi.passandroid.ui.PassViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4774)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4807)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:179)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
	at org.ligi.passandroid.ui.PassViewFragment.M0(SourceFile:35)
	at androidx.fragment.app.Fragment.l1(SourceFile:18)
	at androidx.fragment.app.FragmentStateManager.p(SourceFile:126)
	at androidx.fragment.app.FragmentStateManager.m(SourceFile:64)
	at androidx.fragment.app.FragmentStore.t(SourceFile:31)
	at androidx.fragment.app.FragmentManager.X0(SourceFile:28)
	at androidx.fragment.app.FragmentManager.T(SourceFile:10)
	at androidx.fragment.app.FragmentManager.R(SourceFile:12)
	at androidx.fragment.app.FragmentController.h(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.Z(SourceFile:10)
	at org.ligi.passandroid.ui.PassViewActivity.Z(SourceFile:1)
	at androidx.fragment.app.FragmentActivity.onPostResume(SourceFile:4)
	at androidx.appcompat.app.AppCompatActivity.onPostResume(SourceFile:1)
	at android.app.Activity.performResume(Activity.java:8499)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4764)
	... 13 more
\nLog:  3 current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
3 Writing unhandled exception to: /data/user/0/org.ligi.passandroid/files/3.7.3-1702746299378.tracedroid
```

## workaround

Only happened once and app was afaik usable afterwards. So just use it or restart app.

## system

Device: Fairphone 4 (FP4)  
OS: Android 13, CalyxOS 4.15.0  
source: F-Droid  
Build-ID: `TQ3A.230901.001.23415000`

**Comment by SVNKoch** [comment]
happened to me several times now too. But on re-opening the app again, it didn't crash.
Here is a more up to date stack trace of the same error:
```
file: /data/user/0/org.ligi.passandroid/files/3.7.3-1718116388169.tracedroid
Android Version: 8.1.0
Phone Model: ONEPLUS A5010\nTraceDroid Version: 4.1\nStacktrace: java.lang.RuntimeException: Unable to resume activity {org.ligi.passandroid/org.ligi.passandroid.ui.PassViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3726)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3766)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2995)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
																																   
																												
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
																			
 at android.app.ActivityThread.main(ActivityThread.java:6753)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
 at org.ligi.passandroid.ui.PassViewFragment.M0(SourceFile:35)
 at androidx.fragment.app.Fragment.l1(SourceFile:18)
 at androidx.fragment.app.FragmentStateManager.p(SourceFile:126)
 at androidx.fragment.app.FragmentStateManager.m(SourceFile:64)
 at androidx.fragment.app.FragmentStore.t(SourceFile:31)
 at androidx.fragment.app.FragmentManager.X0(SourceFile:28)
 at androidx.fragment.app.FragmentManager.T(SourceFile:10)
 at androidx.fragment.app.FragmentManager.R(SourceFile:12)
 at androidx.fragment.app.FragmentController.h(Unknown Source:4)
 at androidx.fragment.app.FragmentActivity.Z(SourceFile:10)
 at org.ligi.passandroid.ui.PassViewActivity.Z(SourceFile:1)
 at androidx.fragment.app.FragmentActivity.onPostResume(SourceFile:4)
 at androidx.appcompat.app.AppCompatActivity.onPostResume(SourceFile:1)
 at android.app.Activity.performResume(Activity.java:7168)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3700)
 ... 10 more
\nLog:  3 current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
3 Writing unhandled exception to: /data/user/0/org.ligi.passandroid/files/3.7.3-1718116388169.tracedroid
file: /data/user/0/org.ligi.passandroid/files/3.7.3-1718807271814.tracedroid
Android Version: 8.1.0
Phone Model: ONEPLUS A5010\nTraceDroid Version: 4.1\nStacktrace: java.lang.RuntimeException: Unable to resume activity {org.ligi.passandroid/org.ligi.passandroid.ui.PassViewActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3726)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3766)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2995)
 at android.app.ActivityThread.-wrap11(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6753)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setOnClickListener(android.view.View$OnClickListener)' on a null object reference
 at org.ligi.passandroid.ui.PassViewFragment.M0(SourceFile:35)
 at androidx.fragment.app.Fragment.l1(SourceFile:18)
 at androidx.fragment.app.FragmentStateManager.p(SourceFile:126)
 at androidx.fragment.app.FragmentStateManager.m(SourceFile:64)
 at androidx.fragment.app.FragmentStore.t(SourceFile:31)
 at androidx.fragment.app.FragmentManager.X0(SourceFile:28)
 at androidx.fragment.app.FragmentManager.T(SourceFile:10)
 at androidx.fragment.app.FragmentManager.R(SourceFile:12)
 at androidx.fragment.app.FragmentController.h(Unknown Source:4)
 at androidx.fragment.app.FragmentActivity.Z(SourceFile:10)
 at org.ligi.passandroid.ui.PassViewActivity.Z(SourceFile:1)
 at androidx.fragment.app.FragmentActivity.onPostResume(SourceFile:4)
 at androidx.appcompat.app.AppCompatActivity.onPostResume(SourceFile:1)
 at android.app.Activity.performResume(Activity.java:7168)
 at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3700)
 ... 10 more
\nLog:  3 current handler class=com.android.internal.os.RuntimeInit$KillApplicationHandler
3 Writing unhandled exception to: /data/user/0/org.ligi.passandroid/files/3.7.3-1718807271814.tracedroid
```

**Comment by johnjohndoe** [comment]
:heavy_plus_sign: :one: Same error / stacktrace here with version 3.7.3.

**Comment by z3ntu** [comment]
This is also happening for me (basically?) every time I start the app.
